### ISSUE TITLE
Call `init` on `setup`

### ISSUE THREAD

**Issue by Maksimka101** [f-person/auto-dark-mode.nvim#1]
I think it will be better to do auto init on `setup`.

I have never seen any packages in which I need to call `init` because they starts working when I'm calling `setup`. 
In addition I just missed that in readme and thought that package is broken.

Anyway thanks a lot for this package :)

**Comment by f-person** [comment]
This is something worth considering, however, I'm not sure it's really needed. 

>  In addition I just missed that in readme and thought that package is broken.

This is a good point though :)

**Comment by f-person** [comment]
Not planning to implement this behavior (at least for now)

**Comment by albertnetymk** [comment]
Thank you for this plugin. Maybe you can update the readme of the `vim-plug` part so that the example code contains necessary config. (I am no vim/lua expert, so it took me a while to figure out that I need some explicit `require`s.)

```vimscript
...
Plug 'f-person/auto-dark-mode.nvim'

call plug#end()

lua << EOF
require("auto-dark-mode").setup()
require("auto-dark-mode").init()
EOF
```
