### ISSUE TITLE
Default theme

### ISSUE THREAD

**Issue by Leandros** [f-person/auto-dark-mode.nvim#15]
When used on a remote linux box, `auto-dark-mode` automatically defaults to `background=light`. 

I would prefer to have it default to `background=dark` by specifying a default.

**Comment by nekowinston** [comment]
This was finally introduced by #28 and will be properly documented in a bit. :slightly_smiling_face:

```lua
{
  "f-person/auto-dark-mode.nvim",
  opts = { 
    fallback = "dark" -- either `"dark"` or `"light"`
  }
}
```
