### ISSUE TITLE
Breaks on using nvim with sudo

### ISSUE THREAD

**Issue by KritPaoIn** [f-person/auto-dark-mode.nvim#2]
https://user-images.githubusercontent.com/92923965/190139478-fb0ba886-8e92-41f9-ac6d-28359deca7e6.mov

Code:
```lua
local auto_dark_mode = require("auto-dark-mode")
auto_dark_mode.setup({
update_interval = 4000,
set_light_mode = function()
	theme.light_theme()
        vim.cmd(hls)
end,
set_dark_mode = function()
	theme.dark_theme()
        vim.cmd(hls)
end,
})
auto_dark_mode.init()
```

**Comment by f-person** [comment]
Hi! I'm sorry for not getting back to you sooner. The plugin checks the OS mode by reading UserDefaults:

```sh
defaults read -g AppleInterfaceStyle
```

I guess these are different for your user and root; that's why this happens. Not sure what we can do here

**Comment by f-person** [comment]
BTW, it works correctly if you run sudo while also providing your current user name. So, for `KritPaoIn` it would be
```sh
sudo -u KritPaoIn nvim
```

**Comment by f-person** [comment]
Alright, the plugin will now handle sudo :)
