### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by keelewang** [f-person/auto-dark-mode.nvim#24]
I'm a beginner of nvim. For convenience, I used the configuration provided by [NvChad](https://github.com/NvChad/NvChad) so I don't know how to use this configuration in [NvChad](https://github.com/NvChad/NvChad).

I should have looked for a solution to this problem in nvchad's issues. I have tried [it](https://github.com/NvChad/NvChad/issues/2721) ，but the reply of the maintainer of the project was very casual and there was no specific explanation. He closed it immediately after I put forward the issues. So I came here to find a solution. Thank u : )

This is the profile of plugins.
```lua
local overrides = require("custom.configs.overrides")

local function set_theme(name)
  local cur_theme = require('nvconfig').ui.theme
  require("nvchad.utils").replace_word(cur_theme, name)
  require('nvconfig').ui.theme = name
  require('base46').load_all_highlights()
end


---@type NvPluginSpec[]
local plugins = {

  -- Override plugin definition options

  {
    "neovim/nvim-lspconfig",
    config = function()
      require "plugins.configs.lspconfig"
      require "custom.configs.lspconfig"
    end, -- Override to setup mason-lspconfig
  },

  -- override plugin configs
  {
    "williamboman/mason.nvim",
    opts = overrides.mason
  },

  {
    "nvim-treesitter/nvim-treesitter",
    opts = overrides.treesitter,
  },

  {
    "nvim-tree/nvim-tree.lua",
    opts = overrides.nvimtree,
  },

  -- Install a plugin
  {
    "max397574/better-escape.nvim",
    event = "InsertEnter",
    config = function()
      require("better_escape").setup()
    end,
  },

  {
    "stevearc/conform.nvim",
    --  for users those who want auto-save conform + lazyloading!
    -- event = "BufWritePre"
    config = function()
      require "custom.configs.conform"
    end,
  },

  {
    "f-person/auto-dark-mode.nvim",
    event='VeryLazy',
    config = {
      update_interval = 1000,
      set_dark_mode = function()
        set_theme('onedark')
      end,
      set_light_mode = function()
        set_theme('one_light')
      end,
    },
  }

  -- To make a plugin not be loaded
  -- {
  --   "NvChad/nvim-colorizer.lua",
  --   enabled = false
  -- },

  -- All NvChad plugins are lazy-loaded by default
  -- For a plugin to be loaded, you will need to set either `ft`, `cmd`, `keys`, `event`, or set `lazy = false`
  -- If you want a plugin to load on startup, add `lazy = false` to a plugin spec, for example
  -- {
  --   "mg979/vim-visual-multi",
  --   lazy = false,
  -- }
}

return plugins
```

**Comment by Snuff-red** [comment]
sry, I want to know the way u solve this question? Can u tell me?

**Comment by ke1ewang** [comment]
> sry, I want to know the way u solve this question? Can u tell me?

Replace the auto-dark-mode section above with
`  {
    "f-person/auto-dark-mode.nvim",
    lazy = false,
    config = function ()
      require("auto-dark-mode").setup({
        update_interval = 1000,
      })
    end
  },`

**Comment by Snuff-red** [comment]
> > sry, I want to know the way u solve this question? Can u tell me?
> 
> Replace the auto-dark-mode section above with
> 
> ```
> {
>     "f-person/auto-dark-mode.nvim",
>     lazy = false,
>     config = function ()
>       require("auto-dark-mode").setup({
>         update_interval = 1000,
>       })
>     end
>  },
> ```

I brwoser ur code, unhappy, it has bug on my config. U can see it in my dotfiles. thx , I will solve it later.
