### ISSUE TITLE
Minor Deprecation issue: "Use `Plugin.opts` instead of `Plugin.config`" - PR  (#25) submitted

### ISSUE THREAD

**Issue by skttlock** [f-person/auto-dark-mode.nvim#26]
Hello! Love the plugin, thanks for sharing it with the world.
I am running NeoVim with the Lazy plugin manager, on `:checkhealth:` I receive the following Error/Warning, as stated in the title:
```
- ERROR Issues were reported when loading your specs:                                                                         
- WARNING {auto-dark-mode.nvim}: setting a table to Plugin.config is deprecated. Please use Plugin.opts instead
``` 
 My knowledge and ability to contribute is still prepubescent- my understanding is that this comes from the Readme.md suggested use with Lazy plug. I've submitted a Pull Request, #25 . Let me know if there's anything wrong or anything else I can do.

Thanks!

**Comment by nekowinston** [comment]
Thanks for the PR!
